name: talaria
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  get: ^4.6.5
  sizer: ^2.0.13
  provider: ^6.0.0
  google_fonts: ^4.0.1
  cached_network_image: ^3.2.0
  flutter_widget_from_html: ^0.9.1
  solid_bottom_sheet: ^0.1.10
  flutter_switch: ^0.3.2
  url_launcher: ^6.0.20
  flutter_rating_bar: ^4.0.0
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  firebase_analytics: ^10.1.0
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.1.0
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.1
  google_sign_in: ^5.2.4
  flutter_svg: ^1.0.3
  carousel_slider: ^4.1.1
  images_picker: ^1.2.11
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/images/appIcon.png"
  ios: true
  android: "launcher_icon"
  remove_alpha: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
